name: gestao_bali
description: Gestão de Bolos da Bali

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  provider: ^6.0.2
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
  firebase_auth: ^3.3.4
  firebase_storage: ^10.2.4
  cloud_firestore: ^3.1.5

  shared_preferences: ^2.0.11
  google_sign_in: ^5.2.1

  cached_network_image: ^3.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - resources/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
